# Generated by Django 3.2.8 on 2021-10-05 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, verbose_name='Название магазина')),
                ('description', models.TextField(verbose_name='Описание магазина')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('seller_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace_api.store', verbose_name='Магазин')),
            ],
        ),
    ]
